[package]
name = "doc_build"
version = "0.1.0"
edition = "2024"

[build-dependencies]
app = { path = "../app" }
utoipa-rapidoc = { version = "6.0.0", features = ["actix-web"] }
utoipa = { version = "5.4.0" }

[dependencies]
